steps:
  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '--- Install matrix-is-tester'"
      - "python -m pip install git+https://github.com/matrix-org/matrix-is-tester.git@dbkr/bind_denied_2"
      - "echo '+++ Run Tests'"
      - "PYTHONPATH=`pwd` trial matrix-is-tester"
    label: "matrix-is-tester"
    timeout_in_minutes: 5
    plugins:
      - docker#v3.0.1:
          image: "python:2.7"
    artifact_paths:
      - "matrix_is_test/sydent.stderr"
      - "_trial_temp/test.log"
