name: Docker

on:
  push:
    tags: ["v*"]
    branches: [ main ]

jobs:
  build:
    name: Build and publish images
    uses: "matrix-org/backend-meta/.github/workflows/docker.yml@dmr/docker"
    with:
      image-name: matrixdotorg/sydent
      publish: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
