name: Docker

on:
  push:
    tags: ["v*"]
    branches: [ main, dmr/docker-poetry ]  # TODO remove the latter
  workflow_dispatch:

jobs:
  build:
    name: Build and publish images
    uses: "matrix-org/backend-meta/.github/workflows/docker.yml@dmr/docker"
    with:
      image-name: sydent
      publish: false
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
