name: Docker

on:
  push:
    tags: ["v*"]
    branches: [ main ]

jobs:
  build:
    name: Build and publish images
    uses: "matrix-org/backend-meta/.github/workflows/docker.yml@v1"
    with:
      image-name: matrixdotorg/sydent
      publish: true
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
