name: Docker

on:
  push:
    tags: ["v*"]
    branches: [ main, dmr/docker-poetry ]

jobs:
  build:
    name: Build and publish images
    uses: "matrix-org/backend-meta/.github/workflows/docker.yml@release/v1"
    with:
      image-name: matrixdotorg/sydent
      publish: true
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME_DMRTEST }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN_DMR_TEST }}
